import { Icons } from "@/components/icons"
import type { PageConfig } from "../page-config"
import { statusField, defFields, sc } from "./_helpers"

export const metersConfigs: Record<string, PageConfig> = {
  "meters-relay": {
    id: "meters-relay", title: "Meter Relay", description: "Meter management with relay signals and 11 actions",
    apiEndpoint: "/api/meters",
    serverSide: false, statusField,
    transform: (d: any) => (d.meters || []).map((m: any) => ({
      id: m.id, serial: m.serial || m.meterId || m.id?.slice(0,8) || "—",
      type: m.type || "—", area: m.area || m.location || "—", status: m.status || "active",
      customer: m.customer?.name || "—", readings: m._count?.readings ?? 0,
    })),
    columns: [
      { id: "serial", header: "Serial", accessor: r => r.serial, type: "avatar", width: 180 },
      { id: "type", header: "Type", accessor: r => r.type, type: "badge", width: 100 },
      { id: "area", header: "Area", accessor: r => r.area, width: 140 },
      { id: "status", header: "Status", accessor: r => r.status, type: "status", width: 100 },
      { id: "customer", header: "Customer", accessor: r => r.customer, width: 160 },
    ],
    fields: defFields([]),
    statsCards: [sc("Total", Icons.settings, r=>r.length), sc("Active", Icons.circleCheck, r=>r.filter(x=>x.status==="active").length)],
  },
  meters: {
    id: "meters", title: "Meter Management", description: "Manage all metering devices across all areas",
    apiEndpoint: "/api/meters",
    serverSide: true,
    statusField,
    transform: (d: any) => (d.meters || []).map((m: any) => ({
      id: m.id, serial: m.serial || m.meterId || m.id?.substring(0,8) || "—",
      type: m.type || m.meterType || "LP2", area: m.area || m.location || "—",
      status: m.status || "active", customer: m.customer?.name || "—",
      createdAt: m.createdAt || m.installedAt || "",
    })),
    columns: [
      { id: "serial", header: "Serial", accessor: r => r.serial, type: "avatar", width: 200 },
      { id: "type", header: "Type", accessor: r => r.type, type: "badge", width: 100 },
      { id: "area", header: "Area", accessor: r => r.area, width: 140 },
      { id: "status", header: "Status", accessor: r => r.status, type: "status", width: 120 },
      { id: "customer", header: "Customer", accessor: r => r.customer, width: 160 },
      { id: "createdAt", header: "Installed", accessor: r => r.createdAt, type: "date", width: 110 },
    ],
    fields: defFields([
      { name: "serial", label: "Serial Number", type: "text", required: true, placeholder: "MTR-2024-001" },
      { name: "type", label: "Meter Type", type: "select", options: [
        { value: "electric", label: "Electric" }, { value: "water", label: "Water" }, { value: "gas", label: "Gas" },
      ]},
      { name: "area", label: "Area", type: "text", placeholder: "October, New Cairo, SODIC..." },
      { name: "status", label: "Status", type: "select", options: [
        { value: "active", label: "Active" }, { value: "inactive", label: "Inactive" }, { value: "maintenance", label: "Maintenance" }, { value: "retired", label: "Retired" },
      ]},
    ]),
    statsCards: [sc("Total", Icons.settings, r=>r.length), sc("Active", Icons.circleCheck, r=>r.filter(x=>x.status==="active").length)],
  },
  "meter-types": {
    id: "meter-types", title: "Meter Types", description: "Manage meter type catalog",
    apiEndpoint: "/api/admin/meter-types",
    statusField,
    transform: (d: any) => (d.meterTypes || []).map((t: any) => ({ id: t.id, name: t.name, category: t.category || "", unit: t.unit || "", manufacturer: t.manufacturer || "", formFactor: t.formFactor || "", createdAt: t.createdAt || "" })),
    columns: [
      { id: "name", header: "Name", accessor: r => r.name, type: "avatar", width: 200 },
      { id: "category", header: "Category", accessor: r => r.category, type: "badge", width: 120 },
      { id: "unit", header: "Unit", accessor: r => r.unit, width: 80 },
      { id: "manufacturer", header: "Manufacturer", accessor: r => r.manufacturer || "—", width: 160 },
      { id: "formFactor", header: "Form Factor", accessor: r => r.formFactor || "—", width: 120 },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true, placeholder: "LP2" },
      { name: "category", label: "Category", type: "select", options: [{ value: "electric", label: "Electric" }, { value: "water", label: "Water" }, { value: "gas", label: "Gas" }, { value: "solar", label: "Solar" }] },
      { name: "unit", label: "Unit", type: "text", placeholder: "kWh" },
      { name: "manufacturer", label: "Manufacturer", type: "text", placeholder: "Siemens" },
      { name: "formFactor", label: "Form Factor", type: "text", placeholder: "Three-phase" },
      { name: "description", label: "Description", type: "textarea" },
    ],
    statsCards: [sc("Total", Icons.settings, r=>r.length)],
  },
  consumption: {
    id: "consumption", title: "Consumption View", description: "Meter consumption and usage trends",
    apiEndpoint: "/api/business/pipeline/status",
    serverSide: false, statusField,
    transform: (d: any) => (d.recentRuns || []).map((r: any) => ({
      id: r.id || r.cycle, name: r.cycle || r.name || "Period",
      consumption: r.consumption || r.readings || 0, status: r.status || "active",
      date: r.createdAt || r.date || "",
    })),
    columns: [
      { id: "name", header: "Period", accessor: r => r.name, width: 160 },
      { id: "consumption", header: "Consumption", accessor: r => r.consumption?.toLocaleString?.() || r.consumption, type: "number", width: 120 },
      { id: "status", header: "Status", accessor: r => r.status, type: "status", width: 100 },
      { id: "date", header: "Date", accessor: r => r.date, type: "date", width: 110 },
    ],
    fields: defFields([]),
    statsCards: [sc("Total Periods", Icons.clock, r=>r.length)],
  },
  "batch-validation": {
    id: "batch-validation", title: "Batch Validation", description: "Validate and approve readings in bulk",
    apiEndpoint: "/api/readings/review-queue",
    serverSide: true, statusField,
    transform: (d: any) => (d.readings || d.queue || []).map((r: any) => ({
      id: r.id, meter: r.meterId || r.meter || "—",
      value: r.value || 0, status: r.status || "pending",
      reason: r.message || r.flagReason || "", timestamp: r.timestamp || r.createdAt || "",
    })),
    columns: [
      { id: "meter", header: "Meter", accessor: r => r.meter, width: 180 },
      { id: "value", header: "Reading", accessor: r => r.value, type: "number", width: 100 },
      { id: "reason", header: "Flag Reason", accessor: r => r.reason || "—", width: 200 },
      { id: "status", header: "Status", accessor: r => r.status, type: "status", width: 100 },
      { id: "timestamp", header: "Date", accessor: r => r.timestamp, type: "date", width: 110 },
    ],
    fields: defFields([]),
    statsCards: [sc("Queue", Icons.clock, r=>r.length), sc("Flagged", Icons.circleX, r=>r.filter(x=>x.status==="flagged"||x.status==="suspicious").length)],
  },
  readings: {
    id: "readings", title: "Meter Readings", description: "Consumption readings from all meters",
    apiEndpoint: "/api/readings",
    serverSide: true, resource: "readings",
    statusField,
    transform: (d: any) => (d.readings || []).map((r: any) => ({
      id: r.id, meter: r.meterId || r.meter || "—",
      value: r.value || r.reading || 0, unit: r.unit || "kWh",
      source: r.source || "", status: r.status || "active",
      timestamp: r.timestamp || r.createdAt || "",
    })),
    columns: [
      { id: "meter", header: "Meter", accessor: r => r.meter, type: "avatar", width: 180 },
      { id: "value", header: "Reading", accessor: r => r.value?.toLocaleString?.() || r.value, type: "number", width: 120 },
      { id: "unit", header: "Unit", accessor: r => r.unit, type: "badge", width: 80 },
      { id: "source", header: "Source", accessor: r => r.source || "—", width: 100 },
      { id: "status", header: "Status", accessor: r => r.status, type: "status", width: 100 },
      { id: "timestamp", header: "Date", accessor: r => r.timestamp, type: "date", width: 130 },
    ],
    fields: defFields([
      { name: "meterId", label: "Meter ID", type: "text", required: true, placeholder: "Meter UUID" },
      { name: "value", label: "Reading Value", type: "number", required: true, placeholder: "e.g. 1234.5" },
      { name: "unit", label: "Unit", type: "select", options: [ { value: "kWh", label: "kWh" }, { value: "m3", label: "m³" }, { value: "L", label: "Liters" } ] },
      { name: "source", label: "Source", type: "text", placeholder: "manual, api, import" },
    ]),
    statsCards: [sc("Total", Icons.post, r=>r.length), sc("Valid", Icons.circleCheck, r=>r.filter(x=>x.status==="active").length)],
  },
  "meter-assignments": {
    id: "meter-assignments", title: "Meter Assignments", description: "Manage meter-to-customer assignments",
    apiEndpoint: "/api/meter-assignments",
    serverSide: true,
    statusField,
    transform: (d) => (d.assignments || []).map((a: any) => ({
      id: a.id, meter: a.meter?.serial || a.meterId?.substring(0,8) || "",
      customer: a.customer?.name || a.customerId?.substring(0,8) || "",
      status: a.status || "active", startDate: a.startDate || "", endDate: a.endDate || "",
      createdAt: a.createdAt || "",
    })),
    columns: [
      { id: "meter", header: "Meter", accessor: r => r.meter, type: "avatar", width: 180 },
      { id: "customer", header: "Customer", accessor: r => r.customer, width: 200 },
      { id: "status", header: "Status", accessor: r => r.status, type: "status", width: 120 },
      { id: "startDate", header: "Started", accessor: r => r.startDate, type: "date", width: 120 },
      { id: "endDate", header: "Ended", accessor: r => r.endDate || "", type: "date", width: 120 },
    ],
    fields: [
      { name: "meterId", label: "Meter ID", type: "text", required: true, placeholder: "Enter meter UUID" },
      { name: "customerId", label: "Customer ID", type: "text", required: true, placeholder: "Enter customer UUID" },
      { name: "startDate", label: "Start Date", type: "date" },
      { name: "endDate", label: "End Date", type: "date" },
      { name: "reason", label: "Reason", type: "textarea", placeholder: "Reason for assignment" },
    ],
    statsCards: [sc("Active", Icons.circleCheck, r=>r.filter(x=>x.status==="active").length), sc("Ended", Icons.circleX, r=>r.filter(x=>x.status==="ended").length)],
  },
  "service-connections": {
    id: "service-connections", title: "Service Connections", description: "Meter-to-customer assignments and service points",
    apiEndpoint: "/api/meter-assignments",
    statusField,
    transform: (d) => (d.assignments || []).map((a: any) => ({
      id: a.id, meter: a.meter?.serial || a.meterId?.substring(0,8) || "",
      customer: a.customer?.name || a.customerId?.substring(0,8) || "",
      status: a.status || "active", startDate: a.startDate || "", endDate: a.endDate || "",
      createdAt: a.createdAt || "",
    })),
    columns: [
      { id: "meter", header: "Meter", accessor: r => r.meter, width: 180 },
      { id: "customer", header: "Customer", accessor: r => r.customer, width: 200 },
      { id: "status", header: "Status", accessor: r => r.status, type: "status", width: 120 },
      { id: "startDate", header: "Started", accessor: r => r.startDate, type: "date", width: 120 },
      { id: "endDate", header: "Ended", accessor: r => r.endDate || "", type: "date", width: 120 },
    ],
    fields: [
      { name: "meterId", label: "Meter ID", type: "text", required: true },
      { name: "customerId", label: "Customer ID", type: "text", required: true },
      { name: "startDate", label: "Start Date", type: "date" },
      { name: "endDate", label: "End Date", type: "date" },
    ],
    statsCards: [sc("Active", Icons.circleCheck, r=>r.filter(x=>x.status==="active").length), sc("Ended", Icons.circleX, r=>r.filter(x=>x.status==="ended").length)],
  },
  tariffs: {
    id: "tariffs", title: "Tariffs", description: "Tariff engine with tiered pricing",
    apiEndpoint: "/api/tariffs",
    statusField,
    transform: (d: any) => (d.tariffs || []).map((t: any) => ({
      id: t.id, name: t.name, type: t.type || "—", status: t.status || "active",
      rates: t.rates?.length || 0, tiers: t.tiers?.length || 0,
      createdAt: t.createdAt || "",
    })),
    columns: [
      { id: "name", header: "Name", accessor: r => r.name, width: 220 },
      { id: "type", header: "Type", accessor: r => r.type, width: 120 },
      { id: "rates", header: "Rates", accessor: r => r.rates, width: 80 },
      { id: "tiers", header: "Tiers", accessor: r => r.tiers, width: 80 },
      { id: "status", header: "Status", accessor: r => r.status, type: "status", width: 120 },
      { id: "createdAt", header: "Created", accessor: r => r.createdAt ? new Date(r.createdAt).toLocaleDateString() : "—", width: 120 },
    ],
    fields: defFields([{ name: "name", label: "Name", type: "text", required: true }, { name: "type", label: "Type", type: "select", options: [{ value: "Electricity", label: "Electricity" }, { value: "Water", label: "Water" }, { value: "Gas", label: "Gas" }, { value: "Solar", label: "Solar" }, { value: "BTU", label: "BTU" }] }]),
    statsCards: [],
  },
  sim: {
    id: "sim", title: "SIM Cards", description: "SIM card inventory and assignments",
    apiEndpoint: "/api/sim",
    serverSide: true, resource: "sim",
    statusField,
    transform: (d: any) => (d.sims || []).map((s: any) => ({
      id: s.id, iccid: s.iccid, simNumber: s.simNumber,
      operator: s.operator || "—", status: s.status || "available",
      ipAddress: s.ipAddress || "—", meterId: s.meter?.serial || s.meterId || "",
      cooldownUntil: s.cooldownUntil || "", createdAt: s.createdAt || "",
    })),
    columns: [
      { id: "iccid", header: "ICCID", accessor: r => r.iccid, width: 200 },
      { id: "simNumber", header: "SIM #", accessor: r => r.simNumber, width: 150 },
      { id: "operator", header: "Operator", accessor: r => r.operator, width: 100 },
      { id: "status", header: "Status", accessor: r => r.status, type: "status", width: 100 },
      { id: "meterId", header: "Meter", accessor: r => r.meterId || "—", width: 120 },
      { id: "cooldownUntil", header: "Cooldown", accessor: r => r.cooldownUntil ? new Date(r.cooldownUntil).toLocaleDateString() : "—", width: 110 },
      { id: "createdAt", header: "Created", accessor: r => r.createdAt ? new Date(r.createdAt).toLocaleDateString() : "—", width: 100 },
    ],
    fields: defFields([
      { name: "iccid", label: "ICCID", type: "text", required: true, placeholder: "89000000000000000000" },
      { name: "simNumber", label: "SIM Number", type: "text", required: true, placeholder: "SIM-001" },
      { name: "operator", label: "Operator", type: "text", placeholder: "Vodafone" },
      { name: "ipAddress", label: "IP Address", type: "text", placeholder: "10.0.0.1" },
      { name: "status", label: "Status", type: "select", options: [
        { value: "available", label: "Available" }, { value: "assigned", label: "Assigned" }, { value: "active", label: "Active" }, { value: "faulty", label: "Faulty" }, { value: "retired", label: "Retired" },
      ]},
    ]),
    statsCards: [sc("Total", Icons.settings, r=>r.length), sc("Available", Icons.circleCheck, r=>r.filter(x=>x.status==="available").length), sc("Assigned", Icons.chevronRight, r=>r.filter(x=>x.status==="assigned"||x.status==="active").length), sc("Cooldown", Icons.clock, r=>r.filter(x=>x.cooldownUntil && new Date(x.cooldownUntil) > new Date()).length)],
  },
  zones: {
    id: "zones", title: "Zones", description: "Manage project zones (location hierarchy)",
    apiEndpoint: "/api/locations/zones",
    statusField,
    transform: (d: any) => (d.zones || []).map((z: any) => ({
      id: z.id, name: z.name, code: z.code,
      project: z.project?.name || z.projectId || "",
      unitCount: z._count?.units || 0,
      description: z.description || "",
      createdAt: z.createdAt || "",
    })),
    columns: [
      { id: "name", header: "Name", accessor: r => r.name, type: "avatar", width: 200 },
      { id: "code", header: "Code", accessor: r => r.code, width: 100 },
      { id: "project", header: "Project", accessor: r => r.project, width: 160 },
      { id: "unitCount", header: "Units", accessor: r => r.unitCount, width: 80 },
      { id: "createdAt", header: "Created", accessor: r => r.createdAt, type: "date", width: 110 },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true, placeholder: "Zone A" },
      { name: "code", label: "Code", type: "text", required: true, placeholder: "ZONE-A" },
      { name: "projectId", label: "Project ID", type: "text", required: true, placeholder: "uuid..." },
      { name: "description", label: "Description", type: "textarea" },
    ],
    statsCards: [sc("Total", Icons.settings, r=>r.length)],
  },
  units: {
    id: "units", title: "Units", description: "Manage units within zones",
    apiEndpoint: "/api/locations/units",
    statusField,
    transform: (d: any) => (d.units || []).map((u: any) => ({
      id: u.id, name: u.name, code: u.code,
      zone: u.zone?.name || u.zoneId || "",
      type: u.type || "",
      area: u.area || "",
      status: u.status || "active",
      customer: u.customer?.name || "",
      createdAt: u.createdAt || "",
    })),
    columns: [
      { id: "name", header: "Name", accessor: r => r.name, type: "avatar", width: 200 },
      { id: "code", header: "Code", accessor: r => r.code, width: 100 },
      { id: "zone", header: "Zone", accessor: r => r.zone, width: 140 },
      { id: "type", header: "Type", accessor: r => r.type, type: "badge", width: 100 },
      { id: "status", header: "Status", accessor: r => r.status, type: "status", width: 100 },
      { id: "customer", header: "Customer", accessor: r => r.customer, width: 140 },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true, placeholder: "Unit 101" },
      { name: "code", label: "Code", type: "text", required: true, placeholder: "U-101" },
      { name: "zoneId", label: "Zone ID", type: "text", required: true, placeholder: "uuid..." },
      { name: "type", label: "Type", type: "select", options: [
        { value: "residential", label: "Residential" }, { value: "commercial", label: "Commercial" },
        { value: "industrial", label: "Industrial" }, { value: "government", label: "Government" },
      ]},
      { name: "area", label: "Area (sqm)", type: "number" },
      { name: "status", label: "Status", type: "select", options: [
        { value: "active", label: "Active" }, { value: "inactive", label: "Inactive" }, { value: "maintenance", label: "Maintenance" },
      ]},
    ],
    statsCards: [sc("Total", Icons.settings, r=>r.length), sc("Active", Icons.circleCheck, r=>r.filter(x=>x.status==="active").length)],
  },
}
