import PDFDocument from "pdfkit"
import fs from "fs"
import path from "path"

const OUTPUT_DIR = process.env.PDF_OUTPUT_DIR || "./pdf-output"
if (!fs.existsSync(OUTPUT_DIR)) fs.mkdirSync(OUTPUT_DIR, { recursive: true })

function amountInWords(num) {
  const units = ["", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]
  const teens = ["ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen"]
  const tens = ["", "", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety"]
  if (num === 0) return "zero"
  const convert = (n) => {
    if (n < 10) return units[n]
    if (n < 20) return teens[n - 10]
    if (n < 100) return tens[Math.floor(n / 10)] + (n % 10 ? " " + units[n % 10] : "")
    if (n < 1000) return units[Math.floor(n / 100)] + " hundred" + (n % 100 ? " " + convert(n % 100) : "")
    return ""
  }
  let result = ""
  if (num >= 1000) { result += convert(Math.floor(num / 1000)) + " thousand "; num %= 1000 }
  if (num >= 100) { result += convert(Math.floor(num / 100)) + " hundred "; num %= 100 }
  if (num > 0) result += convert(num)
  return result.trim() + " EGP"
}

export async function generateInvoicePdf(invoice, customer) {
  const doc = new PDFDocument({ margin: 50, size: "A4" })
  const filename = `invoice-${invoice.number || invoice.id}.pdf`
  const filepath = path.join(OUTPUT_DIR, filename)
  const stream = fs.createWriteStream(filepath)
  doc.pipe(stream)

  doc.fontSize(20).text("INVOICE", { align: "center" })
  doc.moveDown()
  doc.fontSize(10).text(`Invoice #: ${invoice.number || invoice.id}`)
  doc.text(`Date: ${invoice.createdAt ? new Date(invoice.createdAt).toLocaleDateString() : new Date().toLocaleDateString()}`)
  doc.text(`Due Date: ${invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString() : "N/A"}`)
  doc.text(`Status: ${invoice.status || "pending"}`)
  doc.moveDown()

  doc.fontSize(12).text("Customer Information")
  doc.fontSize(10)
  doc.text(`Name: ${customer?.name || "N/A"}`)
  doc.text(`Email: ${customer?.email || "N/A"}`)
  doc.text(`ID: ${customer?.id || "N/A"}`)
  doc.moveDown()

  doc.fontSize(12).text("Amount Due")
  doc.fontSize(16).text(`${(invoice.amount || 0).toFixed(2)} EGP`, { continued: false })
  doc.fontSize(10).text(`Amount in words: ${amountInWords(invoice.amount || 0)}`)
  doc.moveDown()

  doc.fontSize(8).text(`Generated by MeterVerse | Document hash: ${invoice.id.slice(0, 12)}`, { align: "center" })
  doc.end()

  return new Promise((resolve, reject) => {
    stream.on("finish", () => resolve({ filepath, filename }))
    stream.on("error", reject)
  })
}

export async function generateStatementPdf(customer, invoices, payments, balance) {
  const doc = new PDFDocument({ margin: 50, size: "A4" })
  const filename = `statement-${customer.id}.pdf`
  const filepath = path.join(OUTPUT_DIR, filename)
  const stream = fs.createWriteStream(filepath)
  doc.pipe(stream)

  doc.fontSize(20).text("CUSTOMER STATEMENT", { align: "center" })
  doc.moveDown()
  doc.fontSize(10).text(`Customer: ${customer.name || "N/A"}`)
  doc.text(`Email: ${customer.email || "N/A"}`)
  doc.text(`Balance: ${(balance || 0).toFixed(2)} EGP`)
  doc.moveDown()

  doc.fontSize(12).text("Invoice History")
  doc.fontSize(10)
  for (const inv of (invoices || []).slice(0, 20)) {
    doc.text(`${inv.number || inv.id} — ${(inv.amount || 0).toFixed(2)} EGP — ${inv.status || "pending"}`)
  }
  doc.moveDown()

  doc.fontSize(12).text("Payment History")
  doc.fontSize(10)
  for (const pmt of (payments || []).slice(0, 20)) {
    doc.text(`${(pmt.amount || 0).toFixed(2)} EGP via ${pmt.method || "unknown"} — ${pmt.status || "completed"}`)
  }
  doc.moveDown()

  doc.fontSize(10).text(`Closing Balance: ${(balance || 0).toFixed(2)} EGP`)
  doc.fontSize(8).text(`Generated by MeterVerse on ${new Date().toISOString().split("T")[0]}`, { align: "center" })
  doc.end()

  return new Promise((resolve, reject) => {
    stream.on("finish", () => resolve({ filepath, filename }))
    stream.on("error", reject)
  })
}
