declare module "@tabler/icons-react" {
  import { FC, SVGProps } from "react"
  export type IconProps = SVGProps<SVGSVGElement> & { size?: number }
  export type Icon = FC<IconProps>
  export const IconAdjustmentsHorizontal: Icon
  export const IconAlertCircle: Icon
  export const IconAlertTriangle: Icon
  export const IconArrowRight: Icon
  export const IconBell: Icon
  export const IconBold: Icon
  export const IconBox: Icon
  export const IconBrandGithub: Icon
  export const IconBrandTwitter: Icon
  export const IconBrightness: Icon
  export const IconCalendar: Icon
  export const IconCheck: Icon
  export const IconChecks: Icon
  export const IconChevronDown: Icon
  export const IconChevronLeft: Icon
  export const IconChevronRight: Icon
  export const IconChevronsDown: Icon
  export const IconChevronsLeft: Icon
  export const IconChevronsRight: Icon
  export const IconChevronsUp: Icon
  export const IconChevronsUpDown: Icon
  export const IconChevronUp: Icon
  export const IconCircle: Icon
  export const IconCircleCheck: Icon
  export const IconCirclePlus: Icon
  export const IconCircleX: Icon
  export const IconClipboardText: Icon
  export const IconClock: Icon
  export const IconCode: Icon
  export const IconCommand: Icon
  export const IconCreditCard: Icon
  export const IconCrown: Icon
  export const IconDeviceLaptop: Icon
  export const IconDots: Icon
  export const IconDotsVertical: Icon
  export const IconEdit: Icon
  export const IconExternalLink: Icon
  export const IconEyeOff: Icon
  export const IconFile: Icon
  export const IconFileText: Icon
  export const IconFileTypeDoc: Icon
  export const IconFileTypePdf: Icon
  export const IconFileTypeXls: Icon
  export const IconFileZip: Icon
  export const IconFolder: Icon
  export const IconGripVertical: Icon
  export const IconHelpCircle: Icon
  export const IconInfoCircle: Icon
  export const IconItalic: Icon
  export const IconLayoutDashboard: Icon
  export const IconLayoutKanban: Icon
  export const IconLayoutSidebar: Icon
  export const IconLoader2: Icon
  export const IconLock: Icon
  export const IconLogin: Icon
  export const IconLogout: Icon
  export const IconMessage: Icon
  export const IconMinus: Icon
  export const IconMoon: Icon
  export const IconMusic: Icon
  export const IconPalette: Icon
  export const IconPaperclip: Icon
  export const IconPhone: Icon
  export const IconPhoto: Icon
  export const IconPizza: Icon
  export const IconPlus: Icon
  export const IconRosetteDiscountCheck: Icon
  export const IconSearch: Icon
  export const IconSelector: Icon
  export const IconSend: Icon
  export const IconSettings: Icon
  export const IconShare: Icon
  export const IconSlash: Icon
  export const IconSparkles: Icon
  export const IconStack2: Icon
  export const IconStar: Icon
  export const IconSun: Icon
  export const IconTrash: Icon
  export const IconTrendingDown: Icon
  export const IconTrendingUp: Icon
  export const IconTypography: Icon
  export const IconUnderline: Icon
  export const IconUpload: Icon
  export const IconUser: Icon
  export const IconUserCircle: Icon
  export const IconUserEdit: Icon
  export const IconUsers: Icon
  export const IconUserX: Icon
  export const IconVideo: Icon
  export const IconX: Icon
}
