/**
 * MeterVerse Icon Registry
 * Single source of truth for all icons.
 * Lucide icons only. No duplicate imports.
 *
 * Usage: import { icons } from "@/design-system/icons"
 *        <icons.Dashboard className="w-5 h-5" />
 */

import {
  LayoutDashboard,
  Users,
  Gauge,
  FileText,
  DollarSign,
  BarChart3,
  BarChart4,
  Settings,
  Shield,
  Bell,
  Search,
  Bot,
  Terminal,
  ClipboardList,
  Activity,
  TrendingUp,
  Building,
  Building2,
  MapPin,
  FileSignature,
  Globe,
  FilePlus,
  FileMinus,
  Eye,
  Pencil,
  RefreshCw,
  CheckCircle,
  Clock,
  Sliders,
  Map,
  Edit3,
  Zap,
  Upload,
  CheckSquare,
  AlertTriangle,
  Percent,
  Calendar,
  Undo,
  ArrowRightLeft,
  CreditCard,
  Wallet,
  Landmark,
  Undo2,
  BookOpen,
  TrendingDown,
  LineChart,
  Download,
  Key,
  Users2,
  FileSearch,
  KeyRound,
  Languages,
  FileType,
  HardDrive,
  ListChecks,
  FileBadge,
  Mail,
  MessageSquare,
  MessageCircle,
  BellRing,
  Lightbulb,
  ThumbsUp,
  FileJson,
  Radio,
  ListOrdered,
  Database,
  Heart,
  LogIn,
  Smartphone,
  Monitor,
  Lock,
  FileLock,
  FolderTree,
  Contact,
  Headphones,
  type LucideIcon,
} from "lucide-react"

export const icons = {
  Dashboard: LayoutDashboard,
  Customers: Users,
  Meters: Gauge,
  Invoices: FileText,
  Payments: DollarSign,
  Financial: BarChart3,
  Reports: BarChart4,
  Settings,
  Admin: Shield,
  Security: Shield,
  Notifications: Bell,
  Search,
  AI: Bot,
  AIAssistant: Bot,
  Developer: Terminal,
  Readings: ClipboardList,
  Monitoring: Activity,
  Collections: TrendingUp,
  Units: Building2,
  Organizations: Building2,
  Locations: MapPin,
  Contracts: FileSignature,
  Portal: Globe,
  InvoiceGenerate: FilePlus,
  CreditNote: FileMinus,
  Preview: Eye,
  Adjustments: Pencil,
  Replace: RefreshCw,
  Status: CheckCircle,
  History: Clock,
  Calibration: Sliders,
  Map,
  ManualReading: Edit3,
  AutomaticReading: Zap,
  Import: Upload,
  Validate: CheckSquare,
  Anomalies: AlertTriangle,
  Consumption: Activity,
  Tariffs: DollarSign,
  Seasonal: Calendar,
  Taxes: DollarSign,
  Discounts: Percent,
  Rules: FileText,
  BillCycle: RefreshCw,
  Approve: ThumbsUp,
  Rollback: Undo,
  Cash: Wallet,
  Bank: Landmark,
  Online: Globe,
  POS: CreditCard,
  Allocation: ArrowRightLeft,
  Reconciliation: CheckCircle,
  Refunds: Undo2,
  Journal: BookOpen,
  Revenue: TrendingUp,
  Expense: TrendingDown,
  Profit: BarChart4,
  Forecast: LineChart,
  Export: Download,
  Users,
  Roles: Shield,
  Permissions: Key,
  Teams: Users2,
  Audit: FileSearch,
  APIKeys: KeyRound,
  Languages,
  Templates: FileType,
  Backups: HardDrive,
  Jobs: ListChecks,
  License: FileBadge,
  Email: Mail,
  SMS: MessageSquare,
  WhatsApp: MessageCircle,
  Push: BellRing,
  InApp: Bell,
  Insights: Lightbulb,
  Recommendations: ThumbsUp,
  API: FileJson,
  Runtime: Terminal,
  Metadata: FileJson,
  Events: Radio,
  Queues: ListOrdered,
  Database,
  Health: Heart,
  Auth: LogIn,
  MFA: Smartphone,
  Sessions: Monitor,
  Secrets: Lock,
  Encryption: FileLock,
  Groups: FolderTree,
  Contacts: Contact,
  Support: Headphones,
  Logs: FileText,
  Tracing: Activity,
  Cache: Zap,
  Gateway: Terminal,
  Building,
  Building2,
  Globe,
} as const

export type IconName = keyof typeof icons
export type { LucideIcon }
