import { Router } from "express"
import { prisma } from "../server.js"
import { authenticate } from "../middleware/auth.js"
import { requirePermission, auditLog } from "../middleware/security.js"
import { z } from "zod"

const router = Router()
router.use(authenticate)
const reportSchema = z.object({ type: z.string().min(1), format: z.string().default('html'), filters: z.any().optional() })

const JAVA_ENGINE_URL = process.env.REPORTING_ENGINE_URL

// ─── REAL-TIME REPORT GENERATION (Node.js fallback) ──────────────────

function generateReportHtml(title, data, format) {
  const rows = data.map((row, i) => {
    const cells = Object.values(row).map(v => `<td style="border:1px solid #ddd;padding:6px;text-align:${typeof v === 'number' ? 'right' : 'left'}">${v ?? ""}</td>`).join("")
    return `<tr${i % 2 === 0 ? ' style="background:#f9f9f9"' : ""}>${cells}</tr>`
  }).join("\n")
  const headers = data.length > 0 ? Object.keys(data[0]).map(k => `<th style="border:1px solid #ddd;padding:8px;background:#005f4e;color:white;font-weight:600">${k}</th>`).join("") : ""

  return `<!DOCTYPE html><html dir="${title.includes("عربي") ? "rtl" : "ltr"}"><head><meta charset="utf-8"><title>${title}</title>
<style>body{font-family:'DejaVu Sans',Arial,sans-serif;font-size:11pt;margin:20px;color:#333}
.header{text-align:center;margin-bottom:20px;padding:15px;border-bottom:2px solid #005f4e}
.header h1{color:#005f4e;margin:0 0 5px 0;font-size:18pt}
.header p{color:#666;margin:0;font-size:9pt}
table{width:100%;border-collapse:collapse;margin-top:10px}
th,td{padding:8px;text-align:left;font-size:9pt}
.footer{text-align:center;margin-top:20px;padding-top:10px;border-top:1px solid #ddd;font-size:8pt;color:#999}
.footer .qr{margin-top:10px}
</style></head><body>
<div class="header"><h1>${title}</h1><p>MeterVerse Enterprise Report — ${new Date().toLocaleDateString()}</p></div>
<table><thead><tr>${headers}</tr></thead><tbody>${rows}</tbody></table>
<div class="footer"><p>Generated by MeterVerse v8.0.0 · Confidential</p></div>
</body></html>`
}

// ─── GENERATE REPORT ─────────────────────────────────────────────────

router.post("/generate", requirePermission("reports.*"), async (req, res, next) => {
  try {
    const { type, format, filters } = reportSchema.parse(req.body)
    if (!type) return res.status(400).json({ error: "Report type required" })

    let data = [], title = type

    switch (type) {
      case "customers":
        data = await prisma.customer.findMany({ where: { archivedAt: null }, take: 100, orderBy: { createdAt: "desc" } })
        title = "Customer Report"
        break
      case "meters":
        data = await prisma.meter.findMany({ where: { archivedAt: null }, take: 100, orderBy: { createdAt: "desc" }, include: { meterType: { select: { name: true } } } })
        data = data.map(m => ({ Serial: m.serial, Type: m.meterType?.name || m.type, Status: m.status, Location: m.location || "—", Area: m.area || "—" }))
        title = "Meter Inventory Report"
        break
      case "invoices":
        data = await prisma.invoice.findMany({ take: 100, orderBy: { createdAt: "desc" }, include: { customer: { select: { name: true } } } })
        data = data.map(i => ({ Number: i.number, Customer: i.customer?.name || "—", Amount: i.amount, Status: i.status, Due: i.dueDate ? new Date(i.dueDate).toLocaleDateString() : "—" }))
        title = "Invoice Report"
        break
      case "readings":
        data = await prisma.reading.findMany({ take: 100, orderBy: { createdAt: "desc" } })
        data = data.map(r => ({ Meter: r.meterId, Value: r.value, Date: r.createdAt ? new Date(r.createdAt).toLocaleDateString() : "—" }))
        title = "Reading Report"
        break
      case "payments":
        data = await prisma.payment.findMany({ take: 100, orderBy: { createdAt: "desc" } })
        data = data.map(p => ({ Method: p.method, Amount: p.amount, Status: p.status, Date: p.createdAt ? new Date(p.createdAt).toLocaleDateString() : "—" }))
        title = "Payment Report"
        break
      case "tariffs":
        data = await prisma.tariff.findMany({ take: 100, orderBy: { name: "asc" }, include: { rates: true } })
        data = data.map(t => ({ Name: t.name, Rate: t.rates?.[0]?.rate || "—", Status: t.status }))
        title = "Tariff Report"
        break
      default:
        // Try Java engine if configured (handles all 44 JRXML templates)
        if (process.env.REPORTING_ENGINE_URL) {
          try {
            const javaRes = await fetch(`${JAVA_ENGINE_URL}/reports/generate`, {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({ type, format, filters }),
              signal: AbortSignal.timeout(15000),
            })
            if (javaRes.ok) {
              const buf = await javaRes.arrayBuffer()
              res.set("Content-Type", format === "pdf" ? "application/pdf" : "text/html")
              res.send(Buffer.from(buf))
              return
            }
          } catch {}
        }
        return res.json({
          note: `Report '${type}' requires JasperReports Java engine. Set REPORTING_ENGINE_URL env var.`,
          availableTemplates: 44,
          templatesPath: "reporting-engine/src/main/resources/reports/",
        })
    }

    const html = generateReportHtml(title, data, format)

    if (format === "pdf") {
      // Use Puppeteer/Playwright for PDF if available, otherwise return HTML
      try {
        const { chromium } = await import("playwright")
        const browser = await chromium.launch({ headless: true })
        const page = await browser.newPage()
        await page.setContent(html, { waitUntil: "networkidle" })
        const pdf = await page.pdf({ format: "A4", margin: { top: "20mm", bottom: "20mm", left: "15mm", right: "15mm" } })
        await browser.close()
        res.set("Content-Type", "application/pdf")
        res.set("Content-Disposition", `attachment; filename="${type}-report.pdf"`)
        res.send(pdf)
      } catch {
        res.send(html)
      }
    } else {
      res.send(html)
    }

    auditLog(req, "report.generated", { type, format })
  } catch (err) { next(err) }
})

// ─── LIST REPORTS ────────────────────────────────────────────────────

router.get("/types", requirePermission("reports.*"), async (req, res) => {
  res.json({
    reports: [
      { id: "customers", title: "Customer Report", description: "List of all customers" },
      { id: "meters", title: "Meter Inventory Report", description: "All meters with types and status" },
      { id: "invoices", title: "Invoice Report", description: "Invoice summary with amounts" },
      { id: "readings", title: "Reading Report", description: "Meter readings log" },
      { id: "payments", title: "Payment Report", description: "Payment transactions" },
      { id: "tariffs", title: "Tariff Report", description: "Tariff rates and plans" },
      { id: "active_tariff", title: "Active Tariff Report", template: "active_tariff.jrxml" },
      { id: "alerts_queue", title: "Alerts Queue", template: "alerts_queue.jrxml" },
      { id: "alerts_sent", title: "Alerts Sent", template: "alerts_sent.jrxml" },
      { id: "canceled_invoices", title: "Canceled Invoices", template: "canceled_invoices.jrxml" },
      { id: "consumption_payments_details", title: "Consumption & Payments Details", template: "consumption_payments_details.jrxml" },
      { id: "customer_aggregated_meter", title: "Customer Aggregated Meter", template: "customer_aggregated_meter.jrxml" },
      { id: "customer_claims", title: "Customer Claims", template: "customer_claims.jrxml" },
      { id: "customer_claims_emaar", title: "Customer Claims (Emaar)", template: "customer_claims_emaar.jrxml" },
      { id: "customer_current_balance", title: "Customer Current Balance", template: "customer_current_balance.jrxml" },
      { id: "customers_details", title: "Customers Details", template: "customers_details.jrxml" },
      { id: "disconnected_meters", title: "Disconnected Meters", template: "disconnected_meters.jrxml" },
      { id: "financial_audit", title: "Financial Audit", template: "financial_audit.jrxml" },
      { id: "invoice_elec", title: "Electricity Invoice", template: "invoice_elec.jrxml" },
      { id: "invoice_water", title: "Water Invoice", template: "invoice_water.jrxml" },
      { id: "invoice_water_new", title: "Water Invoice (New)", template: "invoice_water_new.jrxml" },
      { id: "invoice_water_new_Palm", title: "Water Invoice (Palm Hills)", template: "invoice_water_new_Palm.jrxml" },
      { id: "meter_incorrect_readings", title: "Meter Incorrect Readings", template: "meter_incorrect_readings.jrxml" },
      { id: "meters_details", title: "Meters Details", template: "meters_details.jrxml" },
      { id: "meters_status", title: "Meters Status", template: "meters_status.jrxml" },
      { id: "monthly_consumption", title: "Monthly Consumption", template: "monthly_consumption.jrxml" },
      { id: "monthly_consumption_steps", title: "Monthly Consumption Steps", template: "monthly_consumption_steps.jrxml" },
      { id: "monthly_finance", title: "Monthly Finance", template: "monthly_finance.jrxml" },
      { id: "monthly_invoices", title: "Monthly Invoices", template: "monthly_invoices.jrxml" },
      { id: "monthly_invoices_sub1", title: "Monthly Invoices Sub 1", template: "monthly_invoices_sub1.jrxml" },
      { id: "payment_receipt", title: "Payment Receipt", template: "payment_receipt.jrxml" },
      { id: "payment_receipt_mini", title: "Payment Receipt (Mini)", template: "payment_receipt_mini.jrxml" },
      { id: "payments_report", title: "Payments Report", template: "payments.jrxml" },
      { id: "sub_report_invoices", title: "Sub Report Invoices", template: "sub_report_invoices.jrxml" },
      { id: "sub_report_payments", title: "Sub Report Payments", template: "sub_report_payments.jrxml" },
      { id: "sub_report_tariff_charge", title: "Sub Report Tariff Charge", template: "sub_report_tariff_charge.jrxml" },
      { id: "sub_report_tariff_charge_detail", title: "Sub Report Tariff Charge Detail", template: "sub_report_tariff_charge_detail.jrxml" },
      { id: "unallocated_meters", title: "Unallocated Meters", template: "unallocated_meters.jrxml" },
      { id: "user_audit_log", title: "User Audit Log", template: "user_audit_log.jrxml" },
      { id: "xx_claims", title: "Claims (Draft)", template: "xx_claims.jrxml" },
      { id: "xx_invoice_elec", title: "Electricity Invoice (Draft)", template: "xx_invoice_elec.jrxml" },
      { id: "xx_invoice_water", title: "Water Invoice (Draft)", template: "xx_invoice_water.jrxml" },
      { id: "xx_payment_receipt", title: "Payment Receipt (Draft)", template: "xx_payment_receipt.jrxml" },
      { id: "xx_prepaid_stmt", title: "Prepaid Statement (Draft)", template: "xx_prepaid_stmt.jrxml" },
    ],
    total: 50,
    javaEngine: process.env.REPORTING_ENGINE_URL ? true : false,
    templatesPath: process.env.REPORTING_ENGINE_URL ? "reporting-engine/src/main/resources/reports/" : "44 JRXML files pre-loaded in engine directory",
  })
})

export { router as jasperBridgeRouter }
