import { Router } from "express"
import { prisma } from "../server.js"
import { authenticate } from "../middleware/auth.js"
import { requirePermission, auditLog } from "../middleware/security.js"
import { z } from "zod"

const router = Router()
router.use(authenticate)

const JAVA_ENGINE_URL = process.env.REPORTING_ENGINE_URL || "http://localhost:8080/api/v1"

// ─── REAL-TIME REPORT GENERATION (Node.js fallback) ──────────────────

function generateReportHtml(title, data, format) {
  const rows = data.map((row, i) => {
    const cells = Object.values(row).map(v => `<td style="border:1px solid #ddd;padding:6px;text-align:${typeof v === 'number' ? 'right' : 'left'}">${v ?? ""}</td>`).join("")
    return `<tr${i % 2 === 0 ? ' style="background:#f9f9f9"' : ""}>${cells}</tr>`
  }).join("\n")
  const headers = data.length > 0 ? Object.keys(data[0]).map(k => `<th style="border:1px solid #ddd;padding:8px;background:#005f4e;color:white;font-weight:600">${k}</th>`).join("") : ""

  return `<!DOCTYPE html><html dir="${title.includes("عربي") ? "rtl" : "ltr"}"><head><meta charset="utf-8"><title>${title}</title>
<style>body{font-family:'DejaVu Sans',Arial,sans-serif;font-size:11pt;margin:20px;color:#333}
.header{text-align:center;margin-bottom:20px;padding:15px;border-bottom:2px solid #005f4e}
.header h1{color:#005f4e;margin:0 0 5px 0;font-size:18pt}
.header p{color:#666;margin:0;font-size:9pt}
table{width:100%;border-collapse:collapse;margin-top:10px}
th,td{padding:8px;text-align:left;font-size:9pt}
.footer{text-align:center;margin-top:20px;padding-top:10px;border-top:1px solid #ddd;font-size:8pt;color:#999}
.footer .qr{margin-top:10px}
</style></head><body>
<div class="header"><h1>${title}</h1><p>MeterVerse Enterprise Report — ${new Date().toLocaleDateString()}</p></div>
<table><thead><tr>${headers}</tr></thead><tbody>${rows}</tbody></table>
<div class="footer"><p>Generated by MeterVerse v8.0.0 · Confidential</p></div>
</body></html>`
}

// ─── GENERATE REPORT ─────────────────────────────────────────────────

router.post("/generate", requirePermission("reports.*"), async (req, res, next) => {
  try {
    const { type, format = "html", filters = {} } = req.body
    if (!type) return res.status(400).json({ error: "Report type required" })

    let data = [], title = type

    switch (type) {
      case "customers":
        data = await prisma.customer.findMany({ where: { archivedAt: null }, take: 100, orderBy: { createdAt: "desc" } })
        title = "Customer Report"
        break
      case "meters":
        data = await prisma.meter.findMany({ where: { archivedAt: null }, take: 100, orderBy: { createdAt: "desc" }, include: { meterType: { select: { name: true } } } })
        data = data.map(m => ({ Serial: m.serial, Type: m.meterType?.name || m.type, Status: m.status, Location: m.location || "—", Area: m.area || "—" }))
        title = "Meter Inventory Report"
        break
      case "invoices":
        data = await prisma.invoice.findMany({ take: 100, orderBy: { createdAt: "desc" }, include: { customer: { select: { name: true } } } })
        data = data.map(i => ({ Number: i.number, Customer: i.customer?.name || "—", Amount: i.amount, Status: i.status, Due: i.dueDate ? new Date(i.dueDate).toLocaleDateString() : "—" }))
        title = "Invoice Report"
        break
      case "readings":
        data = await prisma.reading.findMany({ take: 100, orderBy: { createdAt: "desc" } })
        data = data.map(r => ({ Meter: r.meterId, Value: r.value, Date: r.createdAt ? new Date(r.createdAt).toLocaleDateString() : "—" }))
        title = "Reading Report"
        break
      case "payments":
        data = await prisma.payment.findMany({ take: 100, orderBy: { createdAt: "desc" } })
        data = data.map(p => ({ Method: p.method, Amount: p.amount, Status: p.status, Date: p.createdAt ? new Date(p.createdAt).toLocaleDateString() : "—" }))
        title = "Payment Report"
        break
      case "tariffs":
        data = await prisma.tariff.findMany({ take: 100, orderBy: { name: "asc" }, include: { rates: true } })
        data = data.map(t => ({ Name: t.name, Rate: t.rates?.[0]?.rate || "—", Status: t.status }))
        title = "Tariff Report"
        break
      default:
        // Try Java engine if available
        try {
          const javaRes = await fetch(`${JAVA_ENGINE_URL}/reports/generate`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ type, format, filters }),
            signal: AbortSignal.timeout(5000),
          })
          if (javaRes.ok) {
            const buf = await javaRes.arrayBuffer()
            res.set("Content-Type", format === "pdf" ? "application/pdf" : "text/html")
            res.send(Buffer.from(buf))
            return
          }
        } catch {}
        return res.status(400).json({ error: `Unknown report type: ${type}. Available: customers, meters, invoices, readings, payments, tariffs` })
    }

    const html = generateReportHtml(title, data, format)

    if (format === "pdf") {
      // Use Puppeteer/Playwright for PDF if available, otherwise return HTML
      try {
        const { chromium } = await import("playwright")
        const browser = await chromium.launch({ headless: true })
        const page = await browser.newPage()
        await page.setContent(html, { waitUntil: "networkidle" })
        const pdf = await page.pdf({ format: "A4", margin: { top: "20mm", bottom: "20mm", left: "15mm", right: "15mm" } })
        await browser.close()
        res.set("Content-Type", "application/pdf")
        res.set("Content-Disposition", `attachment; filename="${type}-report.pdf"`)
        res.send(pdf)
      } catch {
        res.send(html)
      }
    } else {
      res.send(html)
    }

    auditLog(req, "report.generated", { type, format })
  } catch (err) { next(err) }
})

// ─── LIST REPORTS ────────────────────────────────────────────────────

router.get("/types", requirePermission("reports.*"), async (req, res) => {
  res.json({
    reports: [
      { id: "customers", title: "Customer Report", description: "List of all customers" },
      { id: "meters", title: "Meter Inventory Report", description: "All meters with types and status" },
      { id: "invoices", title: "Invoice Report", description: "Invoice summary with amounts" },
      { id: "readings", title: "Reading Report", description: "Meter readings log" },
      { id: "payments", title: "Payment Report", description: "Payment transactions" },
      { id: "tariffs", title: "Tariff Report", description: "Tariff rates and plans" },
    ],
    javaEngine: process.env.REPORTING_ENGINE_URL ? true : false,
  })
})

export { router as jasperBridgeRouter }
