-- Add 68 database indexes across 39 models
-- Generated from Prisma schema @@index directives


CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE INDEX "User_roleId_idx" ON "User"("roleId");
CREATE INDEX "User_status_createdAt_idx" ON "User"("status", "createdAt");
CREATE UNIQUE INDEX "Role_name_key" ON "Role"("name");
CREATE UNIQUE INDEX "Permission_name_key" ON "Permission"("name");
CREATE INDEX "PermissionOnRole_permissionId_idx" ON "PermissionOnRole"("permissionId");
CREATE INDEX "AuditEntry_actorId_idx" ON "AuditEntry"("actorId");
CREATE INDEX "AuditEntry_action_timestamp_idx" ON "AuditEntry"("action", "timestamp");
CREATE INDEX "AuditEntry_resource_resourceId_idx" ON "AuditEntry"("resource", "resourceId");
CREATE UNIQUE INDEX "SystemSetting_key_key" ON "SystemSetting"("key");
CREATE UNIQUE INDEX "FeatureFlag_key_key" ON "FeatureFlag"("key");
CREATE UNIQUE INDEX "ApiKey_key_key" ON "ApiKey"("key");
CREATE INDEX "ApiKey_userId_idx" ON "ApiKey"("userId");
CREATE INDEX "ApiKey_active_idx" ON "ApiKey"("active");
CREATE UNIQUE INDEX "Session_token_key" ON "Session"("token");
CREATE INDEX "Session_userId_isActive_idx" ON "Session"("userId", "isActive");
CREATE INDEX "Session_expiresAt_idx" ON "Session"("expiresAt");
CREATE UNIQUE INDEX "Organization_name_key" ON "Organization"("name");
CREATE UNIQUE INDEX "Organization_slug_key" ON "Organization"("slug");
CREATE INDEX "Project_organizationId_status_idx" ON "Project"("organizationId", "status");
CREATE UNIQUE INDEX "NotificationTemplate_key_key" ON "NotificationTemplate"("key");
CREATE UNIQUE INDEX "CacheEntry_key_key" ON "CacheEntry"("key");
CREATE UNIQUE INDEX "License_key_key" ON "License"("key");
CREATE UNIQUE INDEX "BrandingConfig_key_key" ON "BrandingConfig"("key");
CREATE INDEX "KpiSnapshot_kpiId_recordedAt_idx" ON "KpiSnapshot"("kpiId", "recordedAt");
CREATE UNIQUE INDEX "Meter_serial_key" ON "Meter"("serial");
CREATE INDEX "Meter_customerId_idx" ON "Meter"("customerId");
CREATE INDEX "Meter_status_createdAt_idx" ON "Meter"("status", "createdAt");
CREATE INDEX "Reading_meterId_timestamp_idx" ON "Reading"("meterId", "timestamp");
CREATE INDEX "Reading_status_idx" ON "Reading"("status");
CREATE UNIQUE INDEX "Invoice_number_key" ON "Invoice"("number");
CREATE INDEX "Invoice_customerId_status_idx" ON "Invoice"("customerId", "status");
CREATE INDEX "Invoice_status_createdAt_idx" ON "Invoice"("status", "createdAt");
CREATE INDEX "Invoice_dueDate_idx" ON "Invoice"("dueDate");
CREATE INDEX "Payment_invoiceId_status_idx" ON "Payment"("invoiceId", "status");
CREATE INDEX "Payment_paidAt_idx" ON "Payment"("paidAt");
CREATE UNIQUE INDEX "Contract_contractNumber_key" ON "Contract"("contractNumber");
CREATE INDEX "Contract_customerId_status_idx" ON "Contract"("customerId", "status");
CREATE INDEX "Contract_status_createdAt_idx" ON "Contract"("status", "createdAt");
CREATE INDEX "Contract_startDate_idx" ON "Contract"("startDate");
CREATE INDEX "ContractTerm_contractId_idx" ON "ContractTerm"("contractId");
CREATE INDEX "ContractAmendment_contractId_idx" ON "ContractAmendment"("contractId");
CREATE UNIQUE INDEX "Tariff_name_key" ON "Tariff"("name");
CREATE UNIQUE INDEX "Tariff_code_key" ON "Tariff"("code");
CREATE INDEX "TariffRate_tariffId_idx" ON "TariffRate"("tariffId");
CREATE INDEX "TariffTier_tariffId_idx" ON "TariffTier"("tariffId");
CREATE UNIQUE INDEX "BillCycle_code_key" ON "BillCycle"("code");
CREATE INDEX "BillRun_billCycleId_idx" ON "BillRun"("billCycleId");
CREATE INDEX "BillRun_status_createdAt_idx" ON "BillRun"("status", "createdAt");
CREATE INDEX "BillRunHistory_billRunId_idx" ON "BillRunHistory"("billRunId");
CREATE UNIQUE INDEX "ChargeRule_code_key" ON "ChargeRule"("code");
CREATE INDEX "ChargeOverride_chargeRuleId_idx" ON "ChargeOverride"("chargeRuleId");
CREATE INDEX "ChargeOverride_customerId_idx" ON "ChargeOverride"("customerId");
CREATE INDEX "ChargeOverride_contractId_idx" ON "ChargeOverride"("contractId");
CREATE INDEX "InvoiceItem_invoiceId_type_idx" ON "InvoiceItem"("invoiceId", "type");
CREATE INDEX "InvoiceTax_invoiceItemId_idx" ON "InvoiceTax"("invoiceItemId");
CREATE INDEX "DiscountRule_invoiceItemId_idx" ON "DiscountRule"("invoiceItemId");
CREATE INDEX "MeterAssignment_meterId_idx" ON "MeterAssignment"("meterId");
CREATE INDEX "MeterAssignment_customerId_status_idx" ON "MeterAssignment"("customerId", "status");
CREATE INDEX "MeterAssignment_contractId_idx" ON "MeterAssignment"("contractId");
CREATE INDEX "MeterAssignmentHistory_meterAssignmentId_idx" ON "MeterAssignmentHistory"("meterAssignmentId");
CREATE INDEX "MeterEvent_meterId_timestamp_idx" ON "MeterEvent"("meterId", "timestamp");
CREATE INDEX "MeterEvent_type_status_idx" ON "MeterEvent"("type", "status");
CREATE UNIQUE INDEX "ValidationRule_code_key" ON "ValidationRule"("code");
CREATE INDEX "ValidationResult_validationRuleId_idx" ON "ValidationResult"("validationRuleId");
CREATE INDEX "ValidationResult_entityType_entityId_idx" ON "ValidationResult"("entityType", "entityId");
CREATE INDEX "ValidationResult_status_idx" ON "ValidationResult"("status");
CREATE INDEX "WorkflowTransition_workflowStateId_idx" ON "WorkflowTransition"("workflowStateId");
CREATE INDEX "CollectionCase_customerId_status_idx" ON "CollectionCase"("customerId", "status");
CREATE INDEX "CollectionCase_invoiceId_idx" ON "CollectionCase"("invoiceId");
CREATE INDEX "CollectionCase_priority_status_idx" ON "CollectionCase"("priority", "status");
CREATE INDEX "CollectionAction_collectionCaseId_idx" ON "CollectionAction"("collectionCaseId");
CREATE INDEX "PromiseToPay_collectionCaseId_idx" ON "PromiseToPay"("collectionCaseId");
CREATE INDEX "PromiseToPay_status_idx" ON "PromiseToPay"("status");
CREATE INDEX "PaymentTransaction_gatewayId_idx" ON "PaymentTransaction"("gatewayId");
CREATE INDEX "PaymentTransaction_paymentId_idx" ON "PaymentTransaction"("paymentId");
CREATE INDEX "PaymentTransaction_status_createdAt_idx" ON "PaymentTransaction"("status", "createdAt");
CREATE INDEX "GatewayLog_paymentTransactionId_idx" ON "GatewayLog"("paymentTransactionId");
CREATE UNIQUE INDEX "CustomerGroup_name_key" ON "CustomerGroup"("name");
CREATE INDEX "GroupMember_customerGroupId_customerId_idx" ON "GroupMember"("customerGroupId", "customerId");
CREATE INDEX "GroupPricing_customerGroupId_idx" ON "GroupPricing"("customerGroupId");
CREATE INDEX "GroupPricing_tariffId_idx" ON "GroupPricing"("tariffId");
CREATE INDEX "SLABreach_slaId_breachedAt_idx" ON "SLABreach"("slaId", "breachedAt");
CREATE INDEX "SLAEscalation_slaId_idx" ON "SLAEscalation"("slaId");
CREATE INDEX "GroupSLA_customerGroupId_idx" ON "GroupSLA"("customerGroupId");
CREATE INDEX "GroupSLA_slaId_idx" ON "GroupSLA"("slaId");
CREATE INDEX "Alert_alertRuleId_idx" ON "Alert"("alertRuleId");
CREATE INDEX "Alert_entityType_entityId_idx" ON "Alert"("entityType", "entityId");
CREATE INDEX "Alert_status_createdAt_idx" ON "Alert"("status", "createdAt");
CREATE INDEX "EscalationStep_escalationPolicyId_idx" ON "EscalationStep"("escalationPolicyId");


