// Registry Engine — Phase 17C Implementation
// Everything registry-driven. No hardcoded menus, routes, or commands.

export { BaseRegistry } from "./registries/base-registry"
export { RegistryManagerImpl } from "./registries/registry-manager"
export { ProgramRegistry } from "./registries/program-registry"
export { CommandRegistry, BUILTIN_COMMANDS } from "./registries/command-registry"
export { ActionRegistry } from "./registries/action-registry"
export { PanelRegistry } from "./registries/panel-registry"
export { WidgetRegistry } from "./registries/widget-registry"
export { ThemeRegistry } from "./registries/theme-registry"
export { PermissionRegistry, BUILTIN_PERMISSIONS } from "./registries/permission-registry"
export { PluginRegistry } from "./registries/plugin-registry"
export { ContextMenuRegistry } from "./registries/context-menu-registry"
export { RouteRegistry } from "./registries/route-registry"
export { EntityRegistry } from "./registries/entity-registry"
export { DiscoveryEngineImpl } from "./discovery/discovery-engine"

export type { RegistryManager } from "./registries/registry-manager"
export type { ProgramRegistryItem } from "./registries/program-registry"
export type { CommandRegistration, CommandContext, CommandResult } from "./registries/command-registry"
export type { ActionRegistration, ActionContext, ActionResult, ActionType } from "./registries/action-registry"
export type { PanelRegistration, PanelProps } from "./registries/panel-registry"
export type { WidgetRegistration, WidgetProps, DashboardType } from "./registries/widget-registry"
export type { ThemeRegistration, ThemeVariables } from "./registries/theme-registry"
export type { PermissionRegistration, PermissionAction } from "./registries/permission-registry"
export type { PluginRegistration, PluginContributions, PluginStatus } from "./registries/plugin-registry"
export type { ContextMenuRegistration, ContextMenuItem, ContextMenuContext, ContextMenuNode } from "./registries/context-menu-registry"
export type { RouteRegistration, RouteMatch, RouteParam } from "./registries/route-registry"
export type { EntityRegistration, EntityField, FieldType, FieldOption } from "./registries/entity-registry"
export type { Registrable, RegistrationOptions, RegistrationResult, RegistryFilter, RegistrySnapshot, DependencyGraph } from "./contracts/base"
